function addIds(players) {
    return players.map((player, index) => ({
        ...player,
        id: index + 1,
    }));
}

const initialPlayers = [
    {
        firstName: "Chris",
        lastName: "Boateng",
        number: 2,
        position: "Point Guard",
        height: "5'10",
        weight: "69KG",
        hometown: "Gravesend",
        bio: {
            description: "Chris is good",
            points: 100,
            rebounds: 100,
            assist: 100,
            steals: 100,
            fg: 100,
            three: 100,
            freethrow: 100,
        },
        image: "/assets/player-image.png",
        teams: ["mens", "u19"],
        videos: ["-kE-LpXoKqU", "phCG5zJFwbc", "0Hef-K4_1r8"],
        stats: [
            {
                year: 2023,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
            {
                year: 2022,
                pointsPerGame: 17.0,
                fieldGoalPercentage: "37.0%",
                threePointPercentage: "25.0%",
                assistsPerGame: 2.5,
                reboundsPerGame: 6.5,
                stealsPerGame: 4.0,
            },
        ],
        profile: true,
        class: 2025,
    },
    {
        firstName: "Eshar",
        lastName: "Heer",
        number: 5,
        position: "Shooting Guard",
        height: "6'2",
        weight: "69KG",
        hometown: "Gravesend",
        image: "/assets/player-image.png",
        teams: ["mens"],
        videos: ["phCG5zJFwbc", "-kE-LpXoKqU"],
        stats: [
            {
                year: 2023,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
            {
                year: 2022,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
        ],
        profile: true,
        class: 2023,
    },
    {
        firstName: "Daniel",
        lastName: "Adeyemi",
        number: 3,
        position: "Wing",
        height: "6'4",
        weight: "69KG",
        hometown: "Gravesend",
        image: "/assets/player-image.png",
        teams: ["mens", "u19"],
        videos: ["phCG5zJFwbc", "-kE-LpXoKqU"],
        stats: [
            {
                year: 2023,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
            {
                year: 2022,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
        ],
        profile: true,
        class: 2025,
    },
    {
        firstName: "Brian",
        lastName: "Olivers",
        number: 23,
        position: "Combo Guard",
        height: "6'1",
        weight: "69KG",
        hometown: "Gravesend",
        image: "/assets/player-image.png",
        teams: ["mens", "u19"],
        stats: [
            {
                year: 2023,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
            {
                year: 2022,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.1,
                stealsPerGame: 3.9,
            },
        ],
        profile: true,
        class: 2025,
    },
    {
        firstName: "Hugh",
        lastName: "Antwi",
        number: 8,
        position: "Point Guard",
        height: "4'2",
        weight: "1KG",
        hometown: "Gravesend",
        image: "/assets/player-image.png",
        teams: ["u19"],
        videos: ["phCG5zJFwbc", "-kE-LpXoKqU"],
        profile: true,
        class: 2026,
    },
    {
        firstName: "Tegh",
        lastName: "Rai",
        number: 9,
        position: "Guard",
        height: "6'0",
        weight: "2KG",
        hometown: "Gravesend",
        image: "/assets/player-image.png",
        teams: ["u16"],
        class: 2027,
    },
    {
        firstName: "Dan",
        lastName: "Awani",
        number: 8,
        position: "Guard",
        height: "6'2",
        weight: "200KG",
        hometown: "Gravesend",
        image: "/assets/player-image.png",
        teams: ["u16"],
        class: 2027,
    },
    {
        firstName: "Emmanuel",
        lastName: "Emiru",
        height: "6'4",
        number: 4,
        position: "Wing",
        image: "/assets/player-image.png",
        teams: ["portsmouth"],
        profile: false,
        class: 2023,
    },
    {
        firstName: "David",
        lastName: "Opinran",
        height: "6'7",
        number: 30,
        position: "Center",
        image: "/assets/player-image.png",
        teams: ["east anglia"],
        profile: true,
        class: 2022,
    },
    {
        firstName: "Arvind",
        lastName: "Bains",
        height: "5'5",
        number: 123,
        position: "Guard",
        image: "/assets/player-image.png",
        teams: ["u14"],
        profile: false,
        class: 2029,
    },
];

const Players = addIds(initialPlayers);

export { Players };
