function addIds(players) {
    return players.map((player, index) => ({
        ...player,
        id: index + 1,
    }));
}

const initialPlayers = [
    {
        firstName: "Chris",
        lastName: "Boateng",
        number: 2,
        position: "Point Guard",
        height: "5'11",
        weight: "69KG",
        wingspan: "6'5",
        standingReach: "7'7",
        nationality: "Ghanaian/English",
        hometown: "Gravesend",
        bio: {
            description:
                "Chris is an extremely shifty PG with elite handles and the ability to score in volume. He plays with excellent pace in transition and excels at coming off screens or handoff situations. He is a creative player who has a deep understanding of the game and is a coach’s dream to work with. Chris lives in the gym and thrives in competitive environments.",
            points: 100,
            rebounds: 100,
            assist: 100,
            steals: 100,
            fg: 100,
            three: 100,
            freethrow: 100,
        },
        image: "/assets/players/chris-boateng.jpg",
        teams: ["mens", "u19"],
        videos: ["-kE-LpXoKqU", "phCG5zJFwbc", "0Hef-K4_1r8"],
        stats: [
            {
                year: 2023,
                pointsPerGame: 17.7,
                fieldGoalPercentage: "42.1%",
                threePointPercentage: "24.0%",
                assistsPerGame: 4.1,
                reboundsPerGame: 5.7,
                stealsPerGame: 3.9,
            },
            {
                year: 2022,
                pointsPerGame: 17.0,
                fieldGoalPercentage: "37.0%",
                threePointPercentage: "25.0%",
                assistsPerGame: 2.5,
                reboundsPerGame: 6.5,
                stealsPerGame: 4.0,
            },
        ],
        currentSeasonStats: {
            teams: {
                Mens: {
                    pointsPerGame: 16.3,
                    fieldGoalPercentage: "41.1%",
                    threePointPercentage: "27.8%",
                    assistsPerGame: 2.9,
                    reboundsPerGame: 4.2,
                    stealsPerGame: 3.0,
                },
                Academy: {
                    pointsPerGame: 20.2,
                    fieldGoalPercentage: "42.4%",
                    threePointPercentage: "31.6%",
                    assistsPerGame: 5.1,
                    reboundsPerGame: 5.7,
                    stealsPerGame: 4.2,
                },
            },
        },
        honors: [
            { title: "Royals Classic Champion", year: "2023, 2024 & 2025" },
            {
                title: "Royals Classic All-Tournament Team",
                year: "2023, 2024 & 2025",
            },
            { title: "Royals Classic MVP", year: "2024 & 2025" },
            { title: "Kent County League Champion", year: "2022/23 & 2023/24" },
            { title: "Kent County League Finals MVP", year: "2022/23" },
            {
                title: "NBL U18 South East Conference Champion",
                year: "2023/24",
            },
            { title: "Senior Academy MVP", year: "2022/23" },
            {
                title: "Senior Academy ‘Chris Morgan’ Impact Award",
                year: "2023/25",
            },
        ],
        profile: true,
        class: 2025,
    },
    {
        firstName: "Oluwagbuyi",
        lastName: "Eribake",
        number: 21,
        position: "Guard",
        height: "6'3",
        weight: "77KG",
        wingspan: "6'8",
        standingReach: "8'2",
        nationality: "German/Nigerian/English",
        hometown: "Kent",
        bio: {
            description:
                "Olu is an outstanding athlete who plays above his size and can score at all three levels. He is an elite-level shooter and has the intelligence to thrive in any offense. Defensively, he can guard multiple positions, is tenacious on the ball, and leads the team in rebounds per game. Olu has a great work ethic, is hungry to develop, and is a leader on and off the court.",
            points: 100,
            rebounds: 100,
            assist: 100,
            steals: 100,
            fg: 100,
            three: 100,
            freethrow: 100,
        },
        image: "/assets/players/olu-eribake.jpg",
        teams: ["mens", "u19"],
        videos: ["XN6rhGXRAgk", "ksMqd1ugWHo", "SoCkOu6bm28"],
        stats: [
            {
                year: 2023,
                pointsPerGame: 20.5,
                fieldGoalPercentage: "42.9%",
                threePointPercentage: "29.3%",
                assistsPerGame: 2.5,
                reboundsPerGame: 13.4,
                stealsPerGame: 3.7,
            },
            {
                year: 2022,
                pointsPerGame: 16.2,
                fieldGoalPercentage: "37.9%",
                threePointPercentage: "19.4%",
                assistsPerGame: 2.3,
                reboundsPerGame: 15.4,
                stealsPerGame: 3.0,
            },
        ],
        currentSeasonStats: {
            teams: {
                Mens: {
                    pointsPerGame: 15.2,
                    fieldGoalPercentage: "43.1%",
                    threePointPercentage: "28.3%",
                    assistsPerGame: 2.1,
                    reboundsPerGame: 9.9,
                    stealsPerGame: 2.1,
                },
                Academy: {
                    pointsPerGame: 16.6,
                    fieldGoalPercentage: "46.3%",
                    threePointPercentage: "23.4%",
                    assistsPerGame: 2.2,
                    reboundsPerGame: 11.4,
                    stealsPerGame: 3.9,
                },
            },
        },
        profile: true,
        class: 2025,
    },

    // {
    //     firstName: "Eshar",
    //     lastName: "Heer",
    //     number: 5,
    //     position: "Shooting Guard",
    //     height: "6'2",
    //     weight: "69KG",
    //     hometown: "Gravesend",
    //     image: "/assets/player-image.png",
    //     teams: ["mens"],
    //     videos: ["phCG5zJFwbc", "-kE-LpXoKqU"],
    //     stats: [
    //         {
    //             year: 2023,
    //             pointsPerGame: 17.7,
    //             fieldGoalPercentage: "42.1%",
    //             threePointPercentage: "24.0%",
    //             assistsPerGame: 4.1,
    //             reboundsPerGame: 5.1,
    //             stealsPerGame: 3.9,
    //         },
    //         {
    //             year: 2022,
    //             pointsPerGame: 17.7,
    //             fieldGoalPercentage: "42.1%",
    //             threePointPercentage: "24.0%",
    //             assistsPerGame: 4.1,
    //             reboundsPerGame: 5.1,
    //             stealsPerGame: 3.9,
    //         },
    //     ],
    //     profile: true,
    //     class: 2023,
    // },
    // {
    //     firstName: "Daniel",
    //     lastName: "Adeyemi",
    //     number: 3,
    //     position: "Wing",
    //     height: "6'4",
    //     weight: "69KG",
    //     hometown: "Gravesend",
    //     image: "/assets/player-image.png",
    //     teams: ["mens", "u19"],
    //     videos: ["phCG5zJFwbc", "-kE-LpXoKqU"],
    //     stats: [
    //         {
    //             year: 2023,
    //             pointsPerGame: 17.7,
    //             fieldGoalPercentage: "42.1%",
    //             threePointPercentage: "24.0%",
    //             assistsPerGame: 4.1,
    //             reboundsPerGame: 5.1,
    //             stealsPerGame: 3.9,
    //         },
    //         {
    //             year: 2022,
    //             pointsPerGame: 17.7,
    //             fieldGoalPercentage: "42.1%",
    //             threePointPercentage: "24.0%",
    //             assistsPerGame: 4.1,
    //             reboundsPerGame: 5.1,
    //             stealsPerGame: 3.9,
    //         },
    //     ],
    //     profile: true,
    //     class: 2025,
    // },
    // {
    //     firstName: "Brian",
    //     lastName: "Olivers",
    //     number: 23,
    //     position: "Combo Guard",
    //     height: "6'1",
    //     weight: "69KG",
    //     hometown: "Gravesend",
    //     image: "/assets/player-image.png",
    //     teams: ["mens", "u19"],
    //     stats: [
    //         {
    //             year: 2023,
    //             pointsPerGame: 17.7,
    //             fieldGoalPercentage: "42.1%",
    //             threePointPercentage: "24.0%",
    //             assistsPerGame: 4.1,
    //             reboundsPerGame: 5.1,
    //             stealsPerGame: 3.9,
    //         },
    //         {
    //             year: 2022,
    //             pointsPerGame: 17.7,
    //             fieldGoalPercentage: "42.1%",
    //             threePointPercentage: "24.0%",
    //             assistsPerGame: 4.1,
    //             reboundsPerGame: 5.1,
    //             stealsPerGame: 3.9,
    //         },
    //     ],
    //     profile: true,
    //     class: 2025,
    // },
    // {
    //     firstName: "Hugh",
    //     lastName: "Antwi",
    //     number: 8,
    //     position: "Point Guard",
    //     height: "4'2",
    //     weight: "1KG",
    //     hometown: "Gravesend",
    //     image: "/assets/player-image.png",
    //     teams: ["u19"],
    //     videos: ["phCG5zJFwbc", "-kE-LpXoKqU"],
    //     profile: true,
    //     class: 2026,
    // },
    // {
    //     firstName: "Tegh",
    //     lastName: "Rai",
    //     number: 9,
    //     position: "Guard",
    //     height: "6'0",
    //     weight: "2KG",
    //     hometown: "Gravesend",
    //     image: "/assets/player-image.png",
    //     teams: ["u16"],
    //     class: 2027,
    // },
    // {
    //     firstName: "Dan",
    //     lastName: "Awani",
    //     number: 8,
    //     position: "Guard",
    //     height: "6'2",
    //     weight: "200KG",
    //     hometown: "Gravesend",
    //     image: "/assets/player-image.png",
    //     teams: ["u16"],
    //     class: 2027,
    // },
    // {
    //     firstName: "Emmanuel",
    //     lastName: "Emiru",
    //     height: "6'4",
    //     number: 4,
    //     position: "Wing",
    //     image: "/assets/player-image.png",
    //     teams: ["portsmouth"],
    //     profile: false,
    //     class: 2023,
    // },
    // {
    //     firstName: "David",
    //     lastName: "Opinran",
    //     height: "6'7",
    //     number: 30,
    //     position: "Center",
    //     image: "/assets/player-image.png",
    //     teams: ["east anglia"],
    //     profile: true,
    //     class: 2022,
    // },
    // {
    //     firstName: "Arvind",
    //     lastName: "Bains",
    //     height: "5'5",
    //     number: 123,
    //     position: "Guard",
    //     image: "/assets/player-image.png",
    //     teams: ["u14"],
    //     profile: false,
    //     class: 2029,
    // },
];

const Players = addIds(initialPlayers);

export { Players };
